name: knights_management
description: "Knights Management - Council and Assembly Financial Management System"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.3.4
  purchases_flutter: ^6.19.1
  logging: ^1.2.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  pdf: ^3.10.7
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^30.1.4
  share_plus: ^7.2.2
  rxdart: ^0.28.0
  provider: ^6.1.1
  intl: ^0.20.2
  dropdown_search: ^5.0.6
  file_picker: ^10.1.9
  file_selector: ^1.0.3
  http: ^1.2.1
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
    - assets/data/system_programs.json
    - assets/data/form1728p_programs.json
    - assets/forms/fraternal_survey1728_p.pdf
    - assets/forms/audit1_1295_p.pdf
    - assets/forms/audit2_1295_p.pdf
