name: knights_management
description: "Knights Management - Council and Assembly Financial Management System"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^5.6.7
  logging: ^1.2.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  pdf: ^3.10.7
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^23.1.44
  share_plus: ^7.2.1
  rxdart: ^0.28.0
  provider: ^6.1.1
  intl: ^0.18.0
  dropdown_search: ^6.0.2
  file_picker: ^6.1.1
  file_selector: ^1.0.3
  http: ^1.2.1
  file_saver: ^0.2.14
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.15.0

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
    - assets/data/system_programs.json
    - assets/data/form1728p_programs.json
    - assets/forms/fraternal_survey1728_p.pdf
    - assets/forms/audit1_1295_p.pdf
    - assets/forms/audit2_1295_p.pdf
